[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "src/functions"
[build]
  include = ["config/*.json"]
[[redirects]]
  force = true
  from = "/graphql/*"
  status = 200
  to = "/.netlify/functions/graphql/:splat"


